# This file was generated by GoReleaser. DO NOT EDIT.
cask "plakar" do
  desc "Plakar is a secure backup solution for all your data sources, including filesystems, S3 buckets, Cloud resources, SFTP servers, and more."
  homepage "https://plakar.io/"
  version "9.0.0-devel.34342ffa.202212211333"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "plakar"

  on_macos do
    on_intel do
      url "https://github.com/brmzkw/plakar/releases/download/v9.0.0-devel.34342ffa.202212211333/plakar_9.0.0-devel.34342ffa.202212211333_darwin_amd64.tar.gz"
      sha256 "68e39b9e4eb6a000a4b920577cd530d2b21cd9d688ffd83867ea288114f77393"
    end
    on_arm do
      url "https://github.com/brmzkw/plakar/releases/download/v9.0.0-devel.34342ffa.202212211333/plakar_9.0.0-devel.34342ffa.202212211333_darwin_arm64.tar.gz"
      sha256 "d6042fb70ff4612df0b4fb9f4d1c7ec3897cf740957078d599e8113316af0aac"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/brmzkw/plakar/releases/download/v9.0.0-devel.34342ffa.202212211333/plakar_9.0.0-devel.34342ffa.202212211333_linux_amd64.tar.gz"
      sha256 "958f1bb85008cd392a8c3a9d5b817fffc75d7b21ec4779b56bf6b211879a7f20"
    end
    on_arm do
      url "https://github.com/brmzkw/plakar/releases/download/v9.0.0-devel.34342ffa.202212211333/plakar_9.0.0-devel.34342ffa.202212211333_linux_arm64.tar.gz"
      sha256 "324248b2adc354b04008071d9daf2f37b851bb640666f63fdf8c8716a162595e"
    end
  end

  caveats do
    "Run plakar help to get started."
  end

  # No zap stanza required
end
