# This file was generated by GoReleaser. DO NOT EDIT.
cask "plakar" do
  desc "Plakar is a secure backup solution for all your data sources, including filesystems, S3 buckets, Cloud resources, SFTP servers, and more."
  homepage "https://plakar.io/"
  version "1.0.5-devel"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "plakar"

  on_macos do
    on_intel do
      url "https://github.com/brmzkw/plakar/releases/download/v1.0.5-devel/plakar_1.0.5-devel_darwin_amd64.tar.gz"
      sha256 "a4bba133de6e63dccfe8e62999f1dd0cbec291d8676b7aabf3993bc1aae39660"
    end
    on_arm do
      url "https://github.com/brmzkw/plakar/releases/download/v1.0.5-devel/plakar_1.0.5-devel_darwin_arm64.tar.gz"
      sha256 "05a7de496dc1456c0261c151419313f1eb91ba54a4035ab1329ed0f7d1ab9ec5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/brmzkw/plakar/releases/download/v1.0.5-devel/plakar_1.0.5-devel_linux_amd64.tar.gz"
      sha256 "06fd61f9d4f5a40612b6cf179b6137ba97f616972ad8c23e403bdbac280c6b7e"
    end
    on_arm do
      url "https://github.com/brmzkw/plakar/releases/download/v1.0.5-devel/plakar_1.0.5-devel_linux_arm64.tar.gz"
      sha256 "963b3ad99e4fd2c24436cbbc8784262910f89447010404644a2a0ce1ee9374bb"
    end
  end

  caveats do
    "Run plakar help to get started."
  end

  # No zap stanza required
end
