# This file was generated by GoReleaser. DO NOT EDIT.
cask "plakar" do
  desc "Plakar is a secure backup solution for all your data sources, including filesystems, S3 buckets, Cloud resources, SFTP servers, and more."
  homepage "https://plakar.io/"
  version "1.4.0-dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "plakar"

  on_macos do
    on_intel do
      url "https://github.com/brmzkw/plakar/releases/download/v1.4.0-dev/plakar_1.4.0-dev_darwin_amd64.tar.gz"
      sha256 "965c578fabb9feaed81a9f7bbd6c7eee0e94d6754fef9819818bf207ec6d1273"
    end
    on_arm do
      url "https://github.com/brmzkw/plakar/releases/download/v1.4.0-dev/plakar_1.4.0-dev_darwin_arm64.tar.gz"
      sha256 "9119b57f6be826a08506c917bedd8f3fe532460e52b0e42c22fb3f4b7f63f1b5"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/brmzkw/plakar/releases/download/v1.4.0-dev/plakar_1.4.0-dev_linux_amd64.tar.gz"
      sha256 "5f174b463d03ce1003ab8a11bc8c765018f8a8128b2a6bfdf9de586ac93a663f"
    end
    on_arm do
      url "https://github.com/brmzkw/plakar/releases/download/v1.4.0-dev/plakar_1.4.0-dev_linux_arm64.tar.gz"
      sha256 "0bf6c9d24e2d82cb644f6f729a25242e7ee10491dde997b67b32e5744e66455e"
    end
  end

  caveats do
    "Run plakar help to get started."
  end

  # No zap stanza required
end
