# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Plakar < Formula
  desc "Plakar is a secure backup solution for all your data sources, including filesystems, S3 buckets, Cloud resources, SFTP servers, and more."
  homepage "https://plakar.io/"
  version "2.0.7"
  license "ISC"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/brmzkw/plakar/releases/download/v2.0.7/plakar_2.0.7_darwin_amd64.tar.gz"
      sha256 "253d2e354043b9d7872789ec81f277d88870a58d23d482cd6826ca238565a4e5"

      def install
        bin.install "plakar"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/brmzkw/plakar/releases/download/v2.0.7/plakar_2.0.7_darwin_arm64.tar.gz"
      sha256 "152829f5f6b3902c3b75ba6ae575b2732623056585c94f0833c04ef84d26648e"

      def install
        bin.install "plakar"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/brmzkw/plakar/releases/download/v2.0.7/plakar_2.0.7_linux_amd64.tar.gz"
      sha256 "c60ace096ab7d5b8cd0cbb489d9800d00156bc33f37e8a20adb8fe33148a1aee"
      def install
        bin.install "plakar"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/brmzkw/plakar/releases/download/v2.0.7/plakar_2.0.7_linux_arm64.tar.gz"
      sha256 "d0166c3c81e51d4451f5d9dc38bf9502483209e9ded2910cd6fe13fdfa96c67d"
      def install
        bin.install "plakar"
      end
    end
  end

  def caveats
    <<~EOS
      Run plakar help to get started.
    EOS
  end

  test do
    system "#{bin}/plakar version"
  end
end
